### ISSUE TITLE
Missing screenshot showing zero errors

### ISSUE THREAD

**Issue by stevebaros** [LisaClement/Pokedex#1]
You were required to add here a screenshot showing zero errors @LisaClement

**Comment by LisaClement** [comment]
Hi @stevebaros, thanks for rising the issue. 

Please find the screenshot here below: 
<img width="1321" alt="Pokedex screenshot" src="https://user-images.githubusercontent.com/20799857/155547426-59b859f9-3c50-4aba-98f1-c79cd1608e15.png">
